import { Platform, StyleSheet } from 'react-native';

import { themeColors } from '../theme/tokens';

const titleFont = Platform.select({
  android: 'serif',
  default: 'Georgia',
  ios: 'Georgia',
  web: 'Georgia, serif',
});

export const styles = StyleSheet.create({
  additionalOption: {
    backgroundColor: themeColors.surfaceAccent,
    borderRadius: 12,
    padding: 12,
  },
  safeArea: {
    backgroundColor: themeColors.background,
    flex: 1,
  },
  content: {
    alignSelf: 'center',
    flexGrow: 1,
    gap: 16,
    maxWidth: 768,
    paddingBottom: 20,
    paddingHorizontal: 6,
    width: '100%',
  },
  screenHeader: {
    alignItems: 'center',
    borderBottomColor: themeColors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 74,
    paddingHorizontal: 0,
    paddingVertical: 10,
  },
  headerCopy: {
    flex: 1,
    gap: 1,
  },
  contextRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  eyebrow: {
    color: themeColors.foregroundMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  contextName: {
    color: themeColors.foregroundMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  title: {
    color: themeColors.foreground,
    fontFamily: titleFont,
    fontSize: 23,
    fontWeight: '700',
  },
  statusBadge: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  openStatusBadge: {
    backgroundColor: themeColors.statusOpenBadge,
    color: themeColors.statusOpenText,
  },
  closedStatusBadge: {
    backgroundColor: themeColors.statusFreeBadge,
    color: themeColors.statusFreeText,
  },
  cancelledStatusBadge: {
    backgroundColor: themeColors.dangerSurface,
    color: themeColors.dangerText,
  },
  itemsContainer: {
    gap: 16,
  },
  card: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.borderStrong,
    borderRadius: 17,
    borderWidth: 1,
  },
  openItemsSection: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 17,
    borderWidth: 1,
    overflow: 'hidden',
  },
  confirmedItemsSection: {
    backgroundColor: themeColors.surfaceMuted,
    borderColor: themeColors.borderStrong,
    borderRadius: 17,
    borderWidth: 1,
    overflow: 'hidden',
  },
  sectionHeading: {
    borderBottomColor: themeColors.divider,
    borderBottomWidth: 1,
    gap: 4,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  sectionTitle: {
    color: themeColors.foreground,
    fontFamily: titleFont,
    fontSize: 18,
    fontWeight: '700',
  },
  sectionDescription: {
    color: themeColors.foregroundMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  emptyState: {
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 20,
    paddingVertical: 36,
  },
  emptyStateTitle: {
    color: themeColors.foreground,
    fontSize: 16,
    fontWeight: '700',
  },
  emptySectionText: {
    color: themeColors.foregroundMuted,
    fontSize: 13,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  description: {
    color: themeColors.foregroundBody,
    fontSize: 14,
    lineHeight: 20,
  },
  itemRow: {
    borderBottomColor: themeColors.divider,
    borderBottomWidth: 1,
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  itemHeader: {
    alignItems: 'stretch',
    gap: 12,
  },
  confirmedItemHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  itemName: {
    color: themeColors.foreground,
    fontSize: 16,
    fontWeight: '700',
  },
  itemTimestamp: {
    color: themeColors.foregroundMuted,
    fontSize: 12,
  },
  input: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 12,
    borderWidth: 1,
    color: themeColors.foreground,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  confirmedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: themeColors.statusFreeBadge,
    borderRadius: 999,
    color: themeColors.statusFreeText,
    fontSize: 11,
    fontWeight: '700',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  quantityActions: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 8,
  },
  quantityControls: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: themeColors.surfaceMuted,
    borderColor: themeColors.borderStrong,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    padding: 3,
  },
  quantityText: {
    color: themeColors.foreground,
    fontSize: 15,
    fontWeight: '700',
    minWidth: 28,
    textAlign: 'center',
  },
  smallButton: {
    alignItems: 'center',
    backgroundColor: themeColors.surfaceAccent,
    borderRadius: 7,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  dangerSmallButton: {
    backgroundColor: themeColors.dangerSurface,
  },
  smallButtonText: {
    color: themeColors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  confirmDeliveryButton: {
    alignItems: 'center',
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  confirmDeliveryButtonText: {
    color: themeColors.foregroundOnPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  subtotalRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  subtotalLabel: {
    color: themeColors.foregroundMuted,
    fontSize: 13,
  },
  subtotalValue: {
    color: themeColors.foreground,
    fontSize: 14,
    fontWeight: '700',
  },
  totalCard: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.borderStrong,
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 16,
  },
  totalLabel: {
    color: themeColors.foregroundMuted,
    flex: 1,
    fontSize: 13,
  },
  totalText: {
    color: themeColors.foreground,
    fontFamily: titleFont,
    fontSize: 22,
    fontWeight: '700',
  },
  loading: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
    minHeight: 240,
  },
  actions: {
    alignSelf: 'center',
    backgroundColor: themeColors.background,
    borderTopColor: themeColors.borderStrong,
    borderTopWidth: 1,
    gap: 10,
    maxWidth: 768,
    paddingHorizontal: 6,
    paddingVertical: 12,
    width: '100%',
  },
  primaryActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  addProductsAction: {
    flex: 1.8,
  },
  closeTableAction: {
    flex: 1,
  },
  error: {
    backgroundColor: themeColors.dangerSurface,
    borderColor: themeColors.dangerBorder,
    borderRadius: 12,
    borderWidth: 1,
    color: themeColors.dangerText,
    padding: 14,
  },
  notice: {
    backgroundColor: themeColors.statusAwaitingSurface,
    borderColor: themeColors.statusAwaitingBorder,
    borderRadius: 12,
    borderWidth: 1,
    color: themeColors.statusAwaitingText,
    padding: 12,
  },
  button: {
    alignItems: 'center',
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dangerButton: {
    backgroundColor: themeColors.dangerSurface,
    borderColor: themeColors.dangerBorder,
  },
  secondaryButton: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.primary,
  },
  tertiaryButton: {
    backgroundColor: 'transparent',
    borderColor: themeColors.borderStrong,
    minHeight: 44,
    paddingVertical: 8,
  },
  disabledButton: {
    opacity: 0.45,
  },
  pressedButton: {
    opacity: 0.72,
  },
  buttonText: {
    color: themeColors.foregroundOnPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  secondaryButtonText: {
    color: themeColors.primary,
  },
  dangerButtonText: {
    color: themeColors.dangerText,
  },
  tertiaryButtonText: {
    color: themeColors.foregroundMuted,
    fontSize: 12,
  },
});
