import { Platform, StyleSheet } from 'react-native';

import { themeColors } from '../theme/tokens';

const titleFont = Platform.select({
  android: 'serif',
  default: 'Georgia',
  ios: 'Georgia',
  web: 'Georgia, serif',
});

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: themeColors.background,
    flex: 1,
  },
  content: {
    alignSelf: 'center',
    flex: 1,
    gap: 12,
    maxWidth: 768,
    paddingBottom: 14,
    paddingHorizontal: 16,
    width: '100%',
  },
  heading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 62,
    paddingVertical: 8,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: themeColors.surfaceMuted,
    borderColor: themeColors.border,
    borderRadius: 11,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  backButtonText: {
    color: themeColors.titleIcon,
    fontSize: 32,
    fontWeight: '300',
    lineHeight: 34,
  },
  headingCopy: {
    flex: 1,
    gap: 1,
  },
  eyebrow: {
    color: themeColors.foregroundMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  title: {
    color: themeColors.foreground,
    fontFamily: titleFont,
    fontSize: 23,
    fontWeight: '700',
  },
  description: {
    color: themeColors.foregroundBody,
    fontSize: 14,
    lineHeight: 20,
  },
  searchField: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 50,
    paddingHorizontal: 13,
  },
  searchIcon: {
    color: themeColors.icon,
    fontSize: 24,
  },
  searchInput: {
    color: themeColors.foregroundBody,
    flex: 1,
    fontSize: 16,
    paddingVertical: 11,
  },
  categoryChips: {
    alignItems: 'center',
    gap: 8,
    height: 48,
    paddingRight: 4,
  },
  categoryBar: {
    flexGrow: 0,
    flexShrink: 0,
    height: 48,
    overflow: 'hidden',
  },
  categoryScroll: {
    height: 48,
  },
  categoryChip: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    flexShrink: 0,
    minHeight: 44,
    paddingHorizontal: 16,
  },
  activeCategoryChip: {
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
  },
  categoryChipText: {
    color: themeColors.primaryText,
    fontSize: 13,
    fontWeight: '700',
  },
  activeCategoryChipText: {
    color: themeColors.foregroundOnPrimary,
  },
  productList: {
    gap: 9,
    paddingBottom: 8,
    paddingTop: 4,
  },
  productListContainer: {
    flex: 1,
    minHeight: 0,
  },
  productCard: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.borderStrong,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 72,
    paddingHorizontal: 15,
    paddingVertical: 11,
  },
  productInfo: {
    flex: 1,
    gap: 3,
  },
  productName: {
    color: themeColors.foreground,
    fontSize: 16,
    fontWeight: '700',
  },
  quantityText: {
    color: themeColors.statusFreeText,
    fontSize: 12,
    fontWeight: '700',
  },
  quantityControl: {
    alignItems: 'center',
    backgroundColor: themeColors.surfaceAccent,
    borderColor: themeColors.primary,
    borderRadius: 11,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 44,
    overflow: 'hidden',
  },
  quantityControlButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  quantityControlButtonText: {
    color: themeColors.primary,
    fontSize: 20,
    fontWeight: '700',
  },
  quantityControlValue: {
    color: themeColors.foreground,
    fontSize: 15,
    fontWeight: '800',
    minWidth: 28,
    textAlign: 'center',
  },
  emptyResults: {
    borderColor: themeColors.borderStrong,
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 1,
    color: themeColors.foregroundMuted,
    paddingHorizontal: 16,
    paddingVertical: 30,
    textAlign: 'center',
  },
  loading: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
  },
  actions: {
    gap: 12,
  },
  error: {
    backgroundColor: themeColors.dangerSurface,
    borderColor: themeColors.dangerBorder,
    borderRadius: 12,
    borderWidth: 1,
    color: themeColors.dangerText,
    padding: 14,
  },
  messageCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.borderStrong,
    borderRadius: 12,
    borderWidth: 1,
    color: themeColors.foregroundMuted,
    padding: 16,
  },
  button: {
    alignItems: 'center',
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
    borderRadius: 11,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  secondaryButton: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.primary,
  },
  disabledButton: {
    opacity: 0.45,
  },
  pressedButton: {
    opacity: 0.72,
  },
  buttonText: {
    color: themeColors.foregroundOnPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryButtonText: {
    color: themeColors.primary,
  },
});
