import { StyleSheet } from 'react-native';

import {
  themeColors,
  themeRadii,
  themeSpacing,
} from '../theme/tokens';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: themeColors.background,
    flex: 1,
  },
  content: {
    alignSelf: 'center',
    flex: 1,
    gap: themeSpacing.sm,
    maxWidth: 768,
    paddingBottom: 14,
    paddingHorizontal: themeSpacing.mobileMargin,
    width: '100%',
  },
  heading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 62,
    paddingVertical: 8,
  },
  headingCopy: {
    flex: 1,
    gap: 1,
  },
  eyebrow: {
    color: themeColors.foregroundMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  title: {
    color: themeColors.foreground,
    fontSize: 21,
    fontWeight: '700',
  },
  description: {
    color: themeColors.foregroundBody,
    fontSize: 14,
    lineHeight: 20,
  },
  searchField: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: themeRadii.standard,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 50,
    paddingHorizontal: 13,
  },
  searchIcon: {
    color: themeColors.icon,
    fontSize: 22,
  },
  searchInput: {
    color: themeColors.foregroundBody,
    flex: 1,
    fontSize: 15,
    paddingVertical: 11,
  },
  categoryChips: {
    alignItems: 'center',
    gap: 8,
    height: 48,
    paddingRight: 4,
  },
  categoryBar: {
    flexGrow: 0,
    flexShrink: 0,
    height: 48,
    overflow: 'hidden',
  },
  categoryScroll: {
    height: 48,
  },
  categoryChip: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: themeRadii.pill,
    borderWidth: 1,
    justifyContent: 'center',
    flexShrink: 0,
    minHeight: 44,
    paddingHorizontal: 16,
  },
  activeCategoryChip: {
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
  },
  categoryChipText: {
    color: themeColors.primaryText,
    fontSize: 13,
    fontWeight: '700',
  },
  activeCategoryChipText: {
    color: themeColors.foregroundOnPrimary,
  },
  productList: {
    gap: 9,
    paddingBottom: 8,
    paddingTop: 4,
  },
  productListContainer: {
    flex: 1,
    minHeight: 0,
  },
  productCard: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderColor: themeColors.borderStrong,
    borderRadius: themeRadii.standard,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 82,
    paddingHorizontal: 15,
    paddingVertical: 11,
  },
  productInfo: {
    flex: 1,
    gap: 3,
  },
  productActions: {
    alignItems: 'flex-end',
    gap: 6,
  },
  temporaryQuantityLabel: {
    color: themeColors.statusAwaitingText,
    fontSize: 11,
    fontWeight: '700',
  },
  productName: {
    color: themeColors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  quantityText: {
    color: themeColors.statusFreeText,
    fontSize: 12,
    fontWeight: '700',
  },
  quantityControl: {
    alignItems: 'center',
    backgroundColor: themeColors.surfaceAccent,
    borderColor: themeColors.primary,
    borderRadius: themeRadii.standard,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 44,
    overflow: 'hidden',
  },
  quantityControlButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  quantityControlButtonText: {
    color: themeColors.primary,
    fontSize: 18,
    fontWeight: '700',
  },
  quantityControlValue: {
    color: themeColors.foreground,
    fontSize: 15,
    fontWeight: '800',
    minWidth: 28,
    textAlign: 'center',
  },
  emptyResults: {
    borderColor: themeColors.borderStrong,
    borderRadius: themeRadii.compact,
    borderStyle: 'dashed',
    borderWidth: 1,
    color: themeColors.foregroundMuted,
    paddingHorizontal: themeSpacing.mobileMargin,
    paddingVertical: 30,
    textAlign: 'center',
  },
  loading: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
  },
  actions: {
    gap: 12,
  },
  pendingBar: {
    alignItems: 'center',
    backgroundColor: themeColors.surface,
    borderTopColor: themeColors.divider,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: themeSpacing.mobileMargin,
    paddingVertical: 12,
  },
  pendingSummary: {
    flex: 1,
    gap: 2,
  },
  pendingCount: {
    color: themeColors.foreground,
    fontSize: 14,
    fontWeight: '800',
  },
  pendingHint: {
    color: themeColors.foregroundMuted,
    fontSize: 11,
    lineHeight: 15,
  },
  error: {
    backgroundColor: themeColors.dangerSurface,
    borderColor: themeColors.dangerBorder,
    borderRadius: themeRadii.compact,
    borderWidth: 1,
    color: themeColors.dangerText,
    padding: 14,
  },
  messageCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.borderStrong,
    borderRadius: themeRadii.compact,
    borderWidth: 1,
    color: themeColors.foregroundMuted,
    padding: 16,
  },
  button: {
    alignItems: 'center',
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
    borderRadius: themeRadii.standard,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  secondaryButton: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.primary,
  },
  disabledButton: {
    opacity: 0.45,
  },
  pressedButton: {
    opacity: 0.72,
  },
  buttonText: {
    color: themeColors.foregroundOnPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryButtonText: {
    color: themeColors.primary,
  },
});
