import { StyleSheet } from 'react-native';

import { themeColors } from '../theme/tokens';

export const statementStyles = StyleSheet.create({
  actions: { gap: 10 },
  button: {
    alignItems: 'center',
    backgroundColor: themeColors.primary,
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonDisabled: { opacity: 0.45 },
  buttonPressed: { opacity: 0.76 },
  buttonSecondary: { backgroundColor: themeColors.surfaceAccent },
  buttonSecondaryText: { color: themeColors.primaryText },
  buttonText: {
    color: themeColors.foregroundOnPrimary,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  balanceText: {
    color: themeColors.primaryText,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  calendarCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 14,
    overflow: 'hidden',
    padding: 12,
  },
  card: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 150,
    flexGrow: 1,
    gap: 6,
    minHeight: 92,
    padding: 14,
  },
  cardLabel: { color: themeColors.foregroundMuted, fontSize: 13, lineHeight: 18 },
  cardValue: { color: themeColors.foreground, fontSize: 21, fontWeight: '800' },
  clearFilters: { alignSelf: 'flex-start', paddingVertical: 4 },
  clearFiltersText: {
    color: themeColors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  commandCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  commandHeader: { gap: 4 },
  commandName: { color: themeColors.primaryText, fontSize: 15, fontWeight: '700' },
  commandTitle: { color: themeColors.foreground, fontSize: 19, fontWeight: '800' },
  content: {
    alignSelf: 'center',
    flexGrow: 1,
    gap: 18,
    maxWidth: 820,
    padding: 22,
    width: '100%',
  },
  dailyCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 7,
    padding: 16,
  },
  dailyDate: { color: themeColors.foreground, fontSize: 17, fontWeight: '800' },
  dailyMeta: { color: themeColors.foregroundMuted, fontSize: 14, lineHeight: 20 },
  dayGroup: { gap: 10 },
  dayGroupTitle: { color: themeColors.primaryText, fontSize: 17, fontWeight: '800' },
  description: { color: themeColors.foregroundMuted, fontSize: 15, lineHeight: 21 },
  error: {
    backgroundColor: themeColors.dangerSurface,
    borderRadius: 12,
    color: themeColors.dangerText,
    fontSize: 14,
    padding: 12,
  },
  eyebrow: {
    color: themeColors.primary,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  empty: {
    color: themeColors.foregroundMuted,
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 8,
    textAlign: 'center',
  },
  entryBody: { borderTopColor: themeColors.border, borderTopWidth: 1, gap: 8, paddingTop: 14 },
  entryCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 12,
    padding: 16,
  },
  entryHeader: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  entryHeaderCopy: { flex: 1, gap: 4 },
  entryTitle: { color: themeColors.foreground, fontSize: 17, fontWeight: '800' },
  filterCard: {
    backgroundColor: themeColors.surfaceAccent,
    borderRadius: 16,
    gap: 14,
    padding: 14,
  },
  filterChip: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 38,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  filterChipSelected: {
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
  },
  filterChipText: { color: themeColors.primaryText, fontSize: 13, fontWeight: '700' },
  filterChipTextSelected: { color: themeColors.foregroundOnPrimary },
  filterGroup: { gap: 8 },
  filterLabel: { color: themeColors.foreground, fontSize: 14, fontWeight: '800' },
  filterOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  financialDescription: {
    color: themeColors.foreground,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
  },
  heading: { gap: 8 },
  itemName: { color: themeColors.foreground, fontSize: 15, fontWeight: '700' },
  itemRow: { backgroundColor: themeColors.surfaceAccent, borderRadius: 12, gap: 3, padding: 12 },
  itemsTitle: { color: themeColors.foreground, fontSize: 15, fontWeight: '800', marginTop: 4 },
  loading: { alignItems: 'center', gap: 12, paddingVertical: 28 },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  period: {
    color: themeColors.primaryText,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  resultCount: { color: themeColors.foregroundMuted, fontSize: 14, fontWeight: '700' },
  safeArea: { backgroundColor: themeColors.background, flex: 1 },
  section: { gap: 12 },
  sectionTitle: { color: themeColors.foreground, fontSize: 20, fontWeight: '800' },
  chevron: { color: themeColors.primary, fontSize: 24, fontWeight: '800' },
  tab: {
    alignItems: 'center',
    borderRadius: 12,
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  tabSelected: { backgroundColor: themeColors.primary },
  tabText: { color: themeColors.primaryText, fontSize: 15, fontWeight: '800' },
  tabTextSelected: { color: themeColors.foregroundOnPrimary },
  tabs: {
    backgroundColor: themeColors.surfaceAccent,
    borderRadius: 14,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  timeline: { gap: 0 },
  timelineDot: {
    backgroundColor: themeColors.primary,
    borderRadius: 6,
    height: 12,
    marginTop: 20,
    width: 12,
  },
  timelineLine: {
    backgroundColor: themeColors.border,
    flex: 1,
    marginBottom: -20,
    marginTop: 4,
    width: 2,
  },
  timelineRail: { alignItems: 'center', width: 20 },
  timelineRow: { flexDirection: 'row', gap: 8, paddingBottom: 10 },
  title: { color: themeColors.foreground, fontSize: 30, fontWeight: '800' },
});
