import { StyleSheet } from 'react-native';

import { themeColors } from '../theme/tokens';

export const statementStyles = StyleSheet.create({
  actions: { gap: 10 },
  button: {
    alignItems: 'center',
    backgroundColor: themeColors.primary,
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonDisabled: { opacity: 0.45 },
  buttonPressed: { opacity: 0.76 },
  buttonSecondary: { backgroundColor: themeColors.surfaceAccent },
  buttonSecondaryText: { color: themeColors.primaryText },
  buttonText: {
    color: themeColors.foregroundOnPrimary,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  calendarCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 14,
    overflow: 'hidden',
    padding: 12,
  },
  card: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 150,
    flexGrow: 1,
    gap: 6,
    minHeight: 92,
    padding: 14,
  },
  cardLabel: { color: themeColors.foregroundMuted, fontSize: 13, lineHeight: 18 },
  cardValue: { color: themeColors.foreground, fontSize: 21, fontWeight: '800' },
  content: {
    alignSelf: 'center',
    flexGrow: 1,
    gap: 18,
    maxWidth: 820,
    padding: 22,
    width: '100%',
  },
  dailyCard: {
    backgroundColor: themeColors.surface,
    borderColor: themeColors.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 7,
    padding: 16,
  },
  dailyDate: { color: themeColors.foreground, fontSize: 17, fontWeight: '800' },
  dailyMeta: { color: themeColors.foregroundMuted, fontSize: 14, lineHeight: 20 },
  description: { color: themeColors.foregroundMuted, fontSize: 15, lineHeight: 21 },
  error: {
    backgroundColor: themeColors.dangerSurface,
    borderRadius: 12,
    color: themeColors.dangerText,
    fontSize: 14,
    padding: 12,
  },
  eyebrow: {
    color: themeColors.primary,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heading: { gap: 8 },
  loading: { alignItems: 'center', gap: 12, paddingVertical: 28 },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  period: {
    color: themeColors.primaryText,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  safeArea: { backgroundColor: themeColors.background, flex: 1 },
  section: { gap: 12 },
  sectionTitle: { color: themeColors.foreground, fontSize: 20, fontWeight: '800' },
  title: { color: themeColors.foreground, fontSize: 30, fontWeight: '800' },
});
