import { StyleSheet } from 'react-native';

export const statementStyles = StyleSheet.create({
  actions: { gap: 10 },
  button: {
    alignItems: 'center',
    backgroundColor: '#76513d',
    borderRadius: 14,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  buttonDisabled: { opacity: 0.45 },
  buttonPressed: { opacity: 0.76 },
  buttonSecondary: { backgroundColor: '#e9ded5' },
  buttonSecondaryText: { color: '#5b4032' },
  buttonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  calendarCard: {
    backgroundColor: '#fff',
    borderColor: '#ddcbbb',
    borderRadius: 18,
    borderWidth: 1,
    gap: 14,
    overflow: 'hidden',
    padding: 12,
  },
  card: {
    backgroundColor: '#fff',
    borderColor: '#ddcbbb',
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: 150,
    flexGrow: 1,
    gap: 6,
    minHeight: 92,
    padding: 14,
  },
  cardLabel: { color: '#6c5d54', fontSize: 13, lineHeight: 18 },
  cardValue: { color: '#382b25', fontSize: 21, fontWeight: '800' },
  content: {
    alignSelf: 'center',
    flexGrow: 1,
    gap: 18,
    maxWidth: 820,
    padding: 22,
    width: '100%',
  },
  dailyCard: {
    backgroundColor: '#fff',
    borderColor: '#ddcbbb',
    borderRadius: 16,
    borderWidth: 1,
    gap: 7,
    padding: 16,
  },
  dailyDate: { color: '#382b25', fontSize: 17, fontWeight: '800' },
  dailyMeta: { color: '#6c5d54', fontSize: 14, lineHeight: 20 },
  description: { color: '#6c5d54', fontSize: 15, lineHeight: 21 },
  error: {
    backgroundColor: '#fde8e8',
    borderRadius: 12,
    color: '#8c2e2e',
    fontSize: 14,
    padding: 12,
  },
  eyebrow: {
    color: '#8a5f48',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heading: { gap: 8 },
  loading: { alignItems: 'center', gap: 12, paddingVertical: 28 },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  period: {
    color: '#5b4032',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  safeArea: { backgroundColor: '#f7f3ed', flex: 1 },
  section: { gap: 12 },
  sectionTitle: { color: '#382b25', fontSize: 20, fontWeight: '800' },
  title: { color: '#382b25', fontSize: 30, fontWeight: '800' },
});
