ALTER TABLE `Comanda` ADD COLUMN `tableName` VARCHAR(80) NULL;
ALTER TABLE `CreditOrder` MODIFY `source` ENUM('MANUAL', 'TABLE', 'DELIVERY', 'QUICK_SALE') NOT NULL;
ALTER TABLE `Payment` MODIFY `origin` ENUM('TABLE_CHECKOUT', 'CREDIT_INSTALLMENT', 'DELIVERY_CHECKOUT', 'QUICK_SALE_CHECKOUT') NOT NULL;
