export const themeColors = {
  accent: '#d4a853',
  accentPressed: '#bd9140',
  background: '#ffffff',
  border: '#aca9a9',
  borderStrong: '#979797',
  dangerBorder: '#e1b7b1',
  dangerSolid: '#a13f3f',
  dangerSurface: '#f8e5e2',
  dangerText: '#842029',
  divider: '#e4dbd1',
  foreground: '#1f1f1f',
  foregroundBody: '#1f1f1f',
  foregroundMuted: '#4f4f4f',
  foregroundOnPrimary: '#ffffff',
  foregroundSoft: '#686868',
  icon: '#aca9a9',
  message: '#4f4f4f',
  placeholder: '#979797',
  primary: '#65060c',
  primaryActivity: '#65060c',
  primaryText: '#65060c',
  statusAwaitingBadge: '#ead8b5',
  statusAwaitingBorder: '#ffca2c',
  statusAwaitingSurface: '#fff3cd',
  statusAwaitingText: '#6d4d17',
  statusFreeBadge: '#cfe5cb',
  statusFreeBorder: '#75b798',
  statusFreeSurface: '#d1e7dd',
  statusFreeText: '#315f2c',
  statusOpenBadge: '#e9c3bd',
  statusOpenBorder: '#ea868f',
  statusOpenSurface: '#f8d7da',
  statusOpenText: '#7d3029',
  surface: '#ffffff',
  surfaceAccent: '#f7ecdf',
  surfaceMuted: '#fff9fa',
  titleEyebrow: '#65060c',
  titleIcon: '#65060c',
} as const;

export const themeSpacing = {
  base: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
  mobileMargin: 20,
  touchTargetMin: 44,
} as const;

export const themeRadii = {
  compact: 16,
  standard: 22,
  pill: 999,
} as const;

export const themeTypography = {
  display: {
    fontFamily: 'Roboto',
    fontSize: 32,
    fontWeight: '800',
    lineHeight: 38,
  },
  screenTitle: {
    fontFamily: 'Roboto',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  sectionTitle: {
    fontFamily: 'Roboto',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 24,
  },
  body: {
    fontFamily: 'Roboto',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 22,
  },
  label: {
    fontFamily: 'Roboto',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 18,
  },
  auxiliary: {
    fontFamily: 'Roboto',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 16,
  },
} as const;
